spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: micro_dev2
    password: 123
    driver-class-name: oracle.jdbc.driver.OracleDriver

jpa:
  hibernate:
   naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  
